### PR TITLE
Italian translation

### PR DESCRIPTION
**Pull request by amivaleo**

### CODE REVIEW

**Comment by maoschanz** [comment]
I'm changing half of things in the extension, so it was not a great idea to translate it so soon

**Comment by amivaleo** [comment]
I'm sorry, I didn't know.

**Comment by maoschanz** [comment]
No, **I** am sorry, I really should have write a warning somewhere, it's not an actual problem, it just means you will need to redo it next week :/

**Comment by amivaleo** [comment]
It is not a problem.

**Comment by maoschanz** [comment]
Sorry for the wait, I just uploaded the new .pot file, it shouldn't change anymore.

**Comment by amivaleo** [comment]
Is it ok for you if I upload an updated italian translation?

**Comment by maoschanz** [comment]
Yes, it is ok

**Comment by amivaleo** [comment]
Thank you. :)

**Pull request merged**
