### PR TITLE
Turkish Translate Update

### PR DESCRIPTION
**Pull request by SerdarSaglam**

### CODE REVIEW

**Comment by maoschanz** [comment]
i don't remember what i did last month with translations, but your work is already merged

**Comment by SerdarSaglam** [comment]
Hi
appfolders-manager.mo	Update translation	22 days ago
appfolders-manager.po	fix a few translations 7 days ago

Mo file old ?

**Comment by maoschanz** [comment]
sorry, i trust my compilation script a little too much

**Comment by SerdarSaglam** [comment]
Thank you for this nice plugin

**Pull request merged**
