### PR TITLE
Update German

### PR DESCRIPTION
**Pull request by jonnius**

### CODE REVIEW

**Comment by maoschanz** [comment]
are you using a software for generating the .pot file ?

**Comment by jonnius** [comment]
I am using [Poedit](https://poedit.net/) for translation. To generate the pot file:

`xgettext -k_ -kN_ -o locale/appfolders-manager.pot *.js --from-code=UTF-8`

**Comment by maoschanz** [comment]
oh thanks, i was perplex about why each item in the .pot file have been swapped

**Comment by jonnius** [comment]
Did you create the pot file manually?

**Comment by maoschanz** [comment]
i copied-pasted the existing "locale" folder from an other extension, and replace strings with gedit, so this file was probably a "fork" of the pot file you provided last year for "emoji selector"

**Comment by maoschanz** [comment]
Also, don't do that with the Emoji Selector extension, it has things like _( KEYWORDS[i] ) somewhere in the code and it can:
- work perfectly, and you will have three thousand strings to translate
- not work at all and you might be missing some strings

**Comment by jonnius** [comment]
There is always a way to make it work. Editing pot files manually can be quiet a pain and one may do mistakes.

**Pull request merged**
