### PR TITLE
Update Italian translation

### PR DESCRIPTION
**Pull request by amivaleo**
:)

### CODE REVIEW

**Comment by maoschanz** [comment]
i see you forked "gnome-shell-extension-clipboard-indicator" from the version i had on my profile, but this is a fork i already merged, you should contribute to the original project here: https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator

**Comment by amivaleo** [comment]
Ywp! I'm sorry, I was in a rush and made a few things without thinking. :)

**Comment by maoschanz** [comment]
Also, if you installed the upstream version of appfolders-manager for testing your translation, be careful, it's a work-in-progress, and it has some very absurd behaviors, maybe the zipped version i put somewhere is better

**Comment by amivaleo** [comment]
I haven't installed that. I just downloaded the zip archive and updated the translation. 🤔

**Comment by maoschanz** [comment]
Ok, fine then

**Pull request merged**
